version: "3.8"
services:
  kubectlexplorer:
    restart: always
    build:
      context: ./
      cache_from:
        - node:alpine
    container_name: kubectl-explorer
    hostname: kubectl-explorer
    network_mode: bridge
    volumes:
      - ./:/usr/app
    ports:
      - 3000:3000
    environment:
      - SHELL=/bin/bash
      - NODE_ENV=development
      - PORT=3000
    command:
      sh -c 'npm i && npm run start'
